### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by sergeyklay** [gleez/cms#778]
Hi @sandeepone 

Please add Gleez CMS in to the Composer Packagist, and turn on the hook for Travis CI.

**Comment by sandeepone** [comment]
Sure, pretty soon

**Comment by sergeyklay** [comment]
Any changes?

**Comment by sandeepone** [comment]
Sorry for delay
https://packagist.org/packages/gleez/cms

**Comment by sergeyklay** [comment]
:+1: thanks!
